version: '3.8'
services:
  backend:
    build: ./backend
    ports:
        - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    command: python app.py

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
